AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spotify-highlights

  SAM Template for spotify-highlights

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SpotifyArtistsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: spotify_artists/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        TopArtists:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          CLIENT_TOKEN: "fake"
          REFRESH_TOKEN: "fake"
  # Type: AWS::Serverless::SimpleTable
  # Properties:
  #   PrimaryKey: PrimaryKeyObject
  #   ProvisionedThroughput: ProvisionedThroughput
  #   SSESpecification: SSESpecification
  #   TableName: String
  #   Tags: Map

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpotifyArtistsApi:
    Description: "API Gateway endpoint URL for Prod stage for Spotify Artists function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SpotifyArtistsFunction:
    Description: "Spotify Artists Lambda Function ARN"
    Value: !GetAtt SpotifyArtistsFunction.Arn
  SpotifyArtistsFunctionIamRole:
    Description: "Implicit IAM Role created for Spotify Artists function"
    Value: !GetAtt SpotifyArtistsFunctionRole.Arn
